/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourseInstanceAddDTO,
  CourseInstanceDTORequestResponse,
  CourseInstanceUpdateDTO,
  RequestResponse,
} from '../models';
import {
    CourseInstanceAddDTOFromJSON,
    CourseInstanceAddDTOToJSON,
    CourseInstanceDTORequestResponseFromJSON,
    CourseInstanceDTORequestResponseToJSON,
    CourseInstanceUpdateDTOFromJSON,
    CourseInstanceUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiCourseInstanceAddPostRequest {
    courseInstanceAddDTO?: CourseInstanceAddDTO;
}

export interface ApiCourseInstanceDeleteIdDeleteRequest {
    id: string;
}

export interface ApiCourseInstanceGetByIdIdGetRequest {
    id: string;
}

export interface ApiCourseInstanceUpdatePutRequest {
    courseInstanceUpdateDTO?: CourseInstanceUpdateDTO;
}

/**
 * 
 */
export class CourseInstanceApi extends runtime.BaseAPI {

    /**
     */
    async apiCourseInstanceAddPostRaw(requestParameters: ApiCourseInstanceAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CourseInstance/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CourseInstanceAddDTOToJSON(requestParameters.courseInstanceAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCourseInstanceAddPost(requestParameters: ApiCourseInstanceAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCourseInstanceAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCourseInstanceDeleteIdDeleteRaw(requestParameters: ApiCourseInstanceDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiCourseInstanceDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CourseInstance/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCourseInstanceDeleteIdDelete(requestParameters: ApiCourseInstanceDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCourseInstanceDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCourseInstanceGetByIdIdGetRaw(requestParameters: ApiCourseInstanceGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseInstanceDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiCourseInstanceGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CourseInstance/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseInstanceDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCourseInstanceGetByIdIdGet(requestParameters: ApiCourseInstanceGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseInstanceDTORequestResponse> {
        const response = await this.apiCourseInstanceGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCourseInstanceUpdatePutRaw(requestParameters: ApiCourseInstanceUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/CourseInstance/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CourseInstanceUpdateDTOToJSON(requestParameters.courseInstanceUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCourseInstanceUpdatePut(requestParameters: ApiCourseInstanceUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiCourseInstanceUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
