/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LaboratoryAddDTO,
  LaboratoryDTORequestResponse,
  LaboratoryUpdateDTO,
  RequestResponse,
} from '../models';
import {
    LaboratoryAddDTOFromJSON,
    LaboratoryAddDTOToJSON,
    LaboratoryDTORequestResponseFromJSON,
    LaboratoryDTORequestResponseToJSON,
    LaboratoryUpdateDTOFromJSON,
    LaboratoryUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiLaboratoryAddPostRequest {
    laboratoryAddDTO?: LaboratoryAddDTO;
}

export interface ApiLaboratoryDeleteIdDeleteRequest {
    id: string;
}

export interface ApiLaboratoryGetByIdIdGetRequest {
    id: string;
}

export interface ApiLaboratoryGetByNameIdGetRequest {
    assistantName: string;
    id: string;
}

export interface ApiLaboratoryUpdatePutRequest {
    laboratoryUpdateDTO?: LaboratoryUpdateDTO;
}

/**
 * 
 */
export class LaboratoryApi extends runtime.BaseAPI {

    /**
     */
    async apiLaboratoryAddPostRaw(requestParameters: ApiLaboratoryAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Laboratory/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LaboratoryAddDTOToJSON(requestParameters.laboratoryAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryAddPost(requestParameters: ApiLaboratoryAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryDeleteIdDeleteRaw(requestParameters: ApiLaboratoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiLaboratoryDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Laboratory/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryDeleteIdDelete(requestParameters: ApiLaboratoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryGetByIdIdGetRaw(requestParameters: ApiLaboratoryGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LaboratoryDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiLaboratoryGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Laboratory/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LaboratoryDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryGetByIdIdGet(requestParameters: ApiLaboratoryGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LaboratoryDTORequestResponse> {
        const response = await this.apiLaboratoryGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryGetByNameIdGetRaw(requestParameters: ApiLaboratoryGetByNameIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LaboratoryDTORequestResponse>> {
        if (requestParameters.assistantName === null || requestParameters.assistantName === undefined) {
            throw new runtime.RequiredError('assistantName','Required parameter requestParameters.assistantName was null or undefined when calling apiLaboratoryGetByNameIdGet.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiLaboratoryGetByNameIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Laboratory/GetByName/{id}`.replace(`{${"assistantName"}}`, encodeURIComponent(String(requestParameters.assistantName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LaboratoryDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryGetByNameIdGet(requestParameters: ApiLaboratoryGetByNameIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LaboratoryDTORequestResponse> {
        const response = await this.apiLaboratoryGetByNameIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryUpdatePutRaw(requestParameters: ApiLaboratoryUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Laboratory/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LaboratoryUpdateDTOToJSON(requestParameters.laboratoryUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryUpdatePut(requestParameters: ApiLaboratoryUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
