/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BooleanRequestResponse,
  LaboratoryInstanceAddDTO,
  LaboratoryInstanceDTOPagedResponseRequestResponse,
  LaboratoryInstanceDTORequestResponse,
  LaboratoryInstanceUpdateDTO,
  RequestResponse,
  UserToLaboratoryInstanceAddDTO,
} from '../models';
import {
    BooleanRequestResponseFromJSON,
    BooleanRequestResponseToJSON,
    LaboratoryInstanceAddDTOFromJSON,
    LaboratoryInstanceAddDTOToJSON,
    LaboratoryInstanceDTOPagedResponseRequestResponseFromJSON,
    LaboratoryInstanceDTOPagedResponseRequestResponseToJSON,
    LaboratoryInstanceDTORequestResponseFromJSON,
    LaboratoryInstanceDTORequestResponseToJSON,
    LaboratoryInstanceUpdateDTOFromJSON,
    LaboratoryInstanceUpdateDTOToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
    UserToLaboratoryInstanceAddDTOFromJSON,
    UserToLaboratoryInstanceAddDTOToJSON,
} from '../models';

export interface ApiLaboratoryInstanceAddPostRequest {
    laboratoryInstanceAddDTO?: LaboratoryInstanceAddDTO;
}

export interface ApiLaboratoryInstanceAddUserToLaboratoryInstancePostRequest {
    userToLaboratoryInstanceAddDTO?: UserToLaboratoryInstanceAddDTO;
}

export interface ApiLaboratoryInstanceDeleteIdDeleteRequest {
    id: string;
}

export interface ApiLaboratoryInstanceGetByIdIdGetRequest {
    id: string;
}

export interface ApiLaboratoryInstanceGetIsUserInLaboratoryInstanceGetRequest {
    laboratoryInstanceId: string;
    userId: string;
}

export interface ApiLaboratoryInstanceGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiLaboratoryInstanceUpdatePutRequest {
    laboratoryInstanceUpdateDTO?: LaboratoryInstanceUpdateDTO;
}

/**
 * 
 */
export class LaboratoryInstanceApi extends runtime.BaseAPI {

    /**
     */
    async apiLaboratoryInstanceAddPostRaw(requestParameters: ApiLaboratoryInstanceAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LaboratoryInstanceAddDTOToJSON(requestParameters.laboratoryInstanceAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceAddPost(requestParameters: ApiLaboratoryInstanceAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryInstanceAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceAddUserToLaboratoryInstancePostRaw(requestParameters: ApiLaboratoryInstanceAddUserToLaboratoryInstancePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/AddUserToLaboratoryInstance`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToLaboratoryInstanceAddDTOToJSON(requestParameters.userToLaboratoryInstanceAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceAddUserToLaboratoryInstancePost(requestParameters: ApiLaboratoryInstanceAddUserToLaboratoryInstancePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryInstanceAddUserToLaboratoryInstancePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceDeleteIdDeleteRaw(requestParameters: ApiLaboratoryInstanceDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiLaboratoryInstanceDeleteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/Delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceDeleteIdDelete(requestParameters: ApiLaboratoryInstanceDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryInstanceDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceGetByIdIdGetRaw(requestParameters: ApiLaboratoryInstanceGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LaboratoryInstanceDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiLaboratoryInstanceGetByIdIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/GetById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LaboratoryInstanceDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceGetByIdIdGet(requestParameters: ApiLaboratoryInstanceGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LaboratoryInstanceDTORequestResponse> {
        const response = await this.apiLaboratoryInstanceGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceGetIsUserInLaboratoryInstanceGetRaw(requestParameters: ApiLaboratoryInstanceGetIsUserInLaboratoryInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanRequestResponse>> {
        if (requestParameters.laboratoryInstanceId === null || requestParameters.laboratoryInstanceId === undefined) {
            throw new runtime.RequiredError('laboratoryInstanceId','Required parameter requestParameters.laboratoryInstanceId was null or undefined when calling apiLaboratoryInstanceGetIsUserInLaboratoryInstanceGet.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiLaboratoryInstanceGetIsUserInLaboratoryInstanceGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/GetIsUserInLaboratoryInstance`.replace(`{${"LaboratoryInstanceId"}}`, encodeURIComponent(String(requestParameters.laboratoryInstanceId))).replace(`{${"UserId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceGetIsUserInLaboratoryInstanceGet(requestParameters: ApiLaboratoryInstanceGetIsUserInLaboratoryInstanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanRequestResponse> {
        const response = await this.apiLaboratoryInstanceGetIsUserInLaboratoryInstanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceGetPageGetRaw(requestParameters: ApiLaboratoryInstanceGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LaboratoryInstanceDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LaboratoryInstanceDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceGetPageGet(requestParameters: ApiLaboratoryInstanceGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LaboratoryInstanceDTOPagedResponseRequestResponse> {
        const response = await this.apiLaboratoryInstanceGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiLaboratoryInstanceUpdatePutRaw(requestParameters: ApiLaboratoryInstanceUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/LaboratoryInstance/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LaboratoryInstanceUpdateDTOToJSON(requestParameters.laboratoryInstanceUpdateDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiLaboratoryInstanceUpdatePut(requestParameters: ApiLaboratoryInstanceUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiLaboratoryInstanceUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
