/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BooleanRequestResponse
 */
export interface BooleanRequestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BooleanRequestResponse
     */
    readonly response?: boolean;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BooleanRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BooleanRequestResponse interface.
 */
export function instanceOfBooleanRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BooleanRequestResponseFromJSON(json: any): BooleanRequestResponse {
    return BooleanRequestResponseFromJSONTyped(json, false);
}

export function BooleanRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : json['response'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BooleanRequestResponseToJSON(value?: BooleanRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

