/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseInstanceAddDTO
 */
export interface CourseInstanceAddDTO {
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceAddDTO
     */
    courseInstanceDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAddDTO
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CourseInstanceAddDTO interface.
 */
export function instanceOfCourseInstanceAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceAddDTOFromJSON(json: any): CourseInstanceAddDTO {
    return CourseInstanceAddDTOFromJSONTyped(json, false);
}

export function CourseInstanceAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseInstanceDate': !exists(json, 'courseInstanceDate') ? undefined : (new Date(json['courseInstanceDate'])),
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CourseInstanceAddDTOToJSON(value?: CourseInstanceAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseInstanceDate': value.courseInstanceDate === undefined ? undefined : (value.courseInstanceDate.toISOString()),
        'courseId': value.courseId,
        'name': value.name,
        'description': value.description,
    };
}

