/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseInstanceSimpleDTO
 */
export interface CourseInstanceSimpleDTO {
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceSimpleDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceSimpleDTO
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceSimpleDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceSimpleDTO
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceSimpleDTO
     */
    courseInstanceDate?: Date;
}

/**
 * Check if a given object implements the CourseInstanceSimpleDTO interface.
 */
export function instanceOfCourseInstanceSimpleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceSimpleDTOFromJSON(json: any): CourseInstanceSimpleDTO {
    return CourseInstanceSimpleDTOFromJSONTyped(json, false);
}

export function CourseInstanceSimpleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceSimpleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'courseInstanceDate': !exists(json, 'courseInstanceDate') ? undefined : (new Date(json['courseInstanceDate'])),
    };
}

export function CourseInstanceSimpleDTOToJSON(value?: CourseInstanceSimpleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'courseId': value.courseId,
        'name': value.name,
        'description': value.description,
        'courseInstanceDate': value.courseInstanceDate === undefined ? undefined : (value.courseInstanceDate.toISOString()),
    };
}

