/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseInstance } from './CourseInstance';
import {
    CourseInstanceFromJSON,
    CourseInstanceFromJSONTyped,
    CourseInstanceToJSON,
} from './CourseInstance';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface CourseInstanceUser
 */
export interface CourseInstanceUser {
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceUser
     */
    courseInstanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceUser
     */
    userId?: string;
    /**
     * 
     * @type {CourseInstance}
     * @memberof CourseInstanceUser
     */
    courseInstance?: CourseInstance;
    /**
     * 
     * @type {User}
     * @memberof CourseInstanceUser
     */
    user?: User;
}

/**
 * Check if a given object implements the CourseInstanceUser interface.
 */
export function instanceOfCourseInstanceUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceUserFromJSON(json: any): CourseInstanceUser {
    return CourseInstanceUserFromJSONTyped(json, false);
}

export function CourseInstanceUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'courseInstanceId': !exists(json, 'courseInstanceId') ? undefined : json['courseInstanceId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'courseInstance': !exists(json, 'courseInstance') ? undefined : CourseInstanceFromJSON(json['courseInstance']),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function CourseInstanceUserToJSON(value?: CourseInstanceUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'courseInstanceId': value.courseInstanceId,
        'userId': value.userId,
        'courseInstance': CourseInstanceToJSON(value.courseInstance),
        'user': UserToJSON(value.user),
    };
}

