/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseInstance } from './CourseInstance';
import {
    CourseInstanceFromJSON,
    CourseInstanceFromJSONTyped,
    CourseInstanceToJSON,
} from './CourseInstance';
import type { CourseUser } from './CourseUser';
import {
    CourseUserFromJSON,
    CourseUserFromJSONTyped,
    CourseUserToJSON,
} from './CourseUser';
import type { Laboratory } from './Laboratory';
import {
    LaboratoryFromJSON,
    LaboratoryFromJSONTyped,
    LaboratoryToJSON,
} from './Laboratory';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';

/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Course
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Course
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    professorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    startTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    series?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    subjectId?: string;
    /**
     * 
     * @type {Subject}
     * @memberof Course
     */
    subject?: Subject;
    /**
     * 
     * @type {Array<CourseInstance>}
     * @memberof Course
     */
    courseInstances?: Array<CourseInstance> | null;
    /**
     * 
     * @type {Array<Laboratory>}
     * @memberof Course
     */
    laboratories?: Array<Laboratory> | null;
    /**
     * 
     * @type {Array<CourseUser>}
     * @memberof Course
     */
    courseUsers?: Array<CourseUser> | null;
}

/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'professorName': !exists(json, 'professorName') ? undefined : json['professorName'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'series': !exists(json, 'series') ? undefined : json['series'],
        'dayOfWeek': !exists(json, 'dayOfWeek') ? undefined : json['dayOfWeek'],
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'subject': !exists(json, 'subject') ? undefined : SubjectFromJSON(json['subject']),
        'courseInstances': !exists(json, 'courseInstances') ? undefined : (json['courseInstances'] === null ? null : (json['courseInstances'] as Array<any>).map(CourseInstanceFromJSON)),
        'laboratories': !exists(json, 'laboratories') ? undefined : (json['laboratories'] === null ? null : (json['laboratories'] as Array<any>).map(LaboratoryFromJSON)),
        'courseUsers': !exists(json, 'courseUsers') ? undefined : (json['courseUsers'] === null ? null : (json['courseUsers'] as Array<any>).map(CourseUserFromJSON)),
    };
}

export function CourseToJSON(value?: Course | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'professorName': value.professorName,
        'startTime': value.startTime,
        'duration': value.duration,
        'location': value.location,
        'series': value.series,
        'dayOfWeek': value.dayOfWeek,
        'subjectId': value.subjectId,
        'subject': SubjectToJSON(value.subject),
        'courseInstances': value.courseInstances === undefined ? undefined : (value.courseInstances === null ? null : (value.courseInstances as Array<any>).map(CourseInstanceToJSON)),
        'laboratories': value.laboratories === undefined ? undefined : (value.laboratories === null ? null : (value.laboratories as Array<any>).map(LaboratoryToJSON)),
        'courseUsers': value.courseUsers === undefined ? undefined : (value.courseUsers === null ? null : (value.courseUsers as Array<any>).map(CourseUserToJSON)),
    };
}

