/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseDTO } from './CourseDTO';
import {
    CourseDTOFromJSON,
    CourseDTOFromJSONTyped,
    CourseDTOToJSON,
} from './CourseDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CourseDTORequestResponse
 */
export interface CourseDTORequestResponse {
    /**
     * 
     * @type {CourseDTO}
     * @memberof CourseDTORequestResponse
     */
    response?: CourseDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CourseDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CourseDTORequestResponse interface.
 */
export function instanceOfCourseDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseDTORequestResponseFromJSON(json: any): CourseDTORequestResponse {
    return CourseDTORequestResponseFromJSONTyped(json, false);
}

export function CourseDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CourseDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CourseDTORequestResponseToJSON(value?: CourseDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CourseDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

