/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseInstanceAttendanceDTO
 */
export interface CourseInstanceAttendanceDTO {
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAttendanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAttendanceDTO
     */
    subjectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceAttendanceDTO
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceAttendanceDTO
     */
    courseInstanceDate?: Date;
}

/**
 * Check if a given object implements the CourseInstanceAttendanceDTO interface.
 */
export function instanceOfCourseInstanceAttendanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceAttendanceDTOFromJSON(json: any): CourseInstanceAttendanceDTO {
    return CourseInstanceAttendanceDTOFromJSONTyped(json, false);
}

export function CourseInstanceAttendanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceAttendanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'subjectName': !exists(json, 'subjectName') ? undefined : json['subjectName'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'courseInstanceDate': !exists(json, 'courseInstanceDate') ? undefined : (new Date(json['courseInstanceDate'])),
    };
}

export function CourseInstanceAttendanceDTOToJSON(value?: CourseInstanceAttendanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'subjectName': value.subjectName,
        'name': value.name,
        'courseInstanceDate': value.courseInstanceDate === undefined ? undefined : (value.courseInstanceDate.toISOString()),
    };
}

