/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseInstanceSimpleDTO } from './CourseInstanceSimpleDTO';
import {
    CourseInstanceSimpleDTOFromJSON,
    CourseInstanceSimpleDTOFromJSONTyped,
    CourseInstanceSimpleDTOToJSON,
} from './CourseInstanceSimpleDTO';
import type { LaboratorySimpleDTO } from './LaboratorySimpleDTO';
import {
    LaboratorySimpleDTOFromJSON,
    LaboratorySimpleDTOFromJSONTyped,
    LaboratorySimpleDTOToJSON,
} from './LaboratorySimpleDTO';
import type { SubjectSimpleDTO } from './SubjectSimpleDTO';
import {
    SubjectSimpleDTOFromJSON,
    SubjectSimpleDTOFromJSONTyped,
    SubjectSimpleDTOToJSON,
} from './SubjectSimpleDTO';
import type { UserSimpleDTO } from './UserSimpleDTO';
import {
    UserSimpleDTOFromJSON,
    UserSimpleDTOFromJSONTyped,
    UserSimpleDTOToJSON,
} from './UserSimpleDTO';

/**
 * 
 * @export
 * @interface CourseDTO
 */
export interface CourseDTO {
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    professorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    startTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CourseDTO
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    series?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CourseDTO
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseDTO
     */
    subjectId?: string;
    /**
     * 
     * @type {SubjectSimpleDTO}
     * @memberof CourseDTO
     */
    subject?: SubjectSimpleDTO;
    /**
     * 
     * @type {Array<CourseInstanceSimpleDTO>}
     * @memberof CourseDTO
     */
    courseInstances?: Array<CourseInstanceSimpleDTO> | null;
    /**
     * 
     * @type {Array<UserSimpleDTO>}
     * @memberof CourseDTO
     */
    courseUsers?: Array<UserSimpleDTO> | null;
    /**
     * 
     * @type {Array<LaboratorySimpleDTO>}
     * @memberof CourseDTO
     */
    laboratories?: Array<LaboratorySimpleDTO> | null;
}

/**
 * Check if a given object implements the CourseDTO interface.
 */
export function instanceOfCourseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseDTOFromJSON(json: any): CourseDTO {
    return CourseDTOFromJSONTyped(json, false);
}

export function CourseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'professorName': !exists(json, 'professorName') ? undefined : json['professorName'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'series': !exists(json, 'series') ? undefined : json['series'],
        'dayOfWeek': !exists(json, 'dayOfWeek') ? undefined : json['dayOfWeek'],
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'subject': !exists(json, 'subject') ? undefined : SubjectSimpleDTOFromJSON(json['subject']),
        'courseInstances': !exists(json, 'courseInstances') ? undefined : (json['courseInstances'] === null ? null : (json['courseInstances'] as Array<any>).map(CourseInstanceSimpleDTOFromJSON)),
        'courseUsers': !exists(json, 'courseUsers') ? undefined : (json['courseUsers'] === null ? null : (json['courseUsers'] as Array<any>).map(UserSimpleDTOFromJSON)),
        'laboratories': !exists(json, 'laboratories') ? undefined : (json['laboratories'] === null ? null : (json['laboratories'] as Array<any>).map(LaboratorySimpleDTOFromJSON)),
    };
}

export function CourseDTOToJSON(value?: CourseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'professorName': value.professorName,
        'startTime': value.startTime,
        'duration': value.duration,
        'location': value.location,
        'series': value.series,
        'dayOfWeek': value.dayOfWeek,
        'subjectId': value.subjectId,
        'subject': SubjectSimpleDTOToJSON(value.subject),
        'courseInstances': value.courseInstances === undefined ? undefined : (value.courseInstances === null ? null : (value.courseInstances as Array<any>).map(CourseInstanceSimpleDTOToJSON)),
        'courseUsers': value.courseUsers === undefined ? undefined : (value.courseUsers === null ? null : (value.courseUsers as Array<any>).map(UserSimpleDTOToJSON)),
        'laboratories': value.laboratories === undefined ? undefined : (value.laboratories === null ? null : (value.laboratories as Array<any>).map(LaboratorySimpleDTOToJSON)),
    };
}

