/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Course } from './Course';
import {
    CourseFromJSON,
    CourseFromJSONTyped,
    CourseToJSON,
} from './Course';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface CourseUser
 */
export interface CourseUser {
    /**
     * 
     * @type {string}
     * @memberof CourseUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CourseUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseUser
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseUser
     */
    userId?: string;
    /**
     * 
     * @type {Course}
     * @memberof CourseUser
     */
    course?: Course;
    /**
     * 
     * @type {User}
     * @memberof CourseUser
     */
    user?: User;
}

/**
 * Check if a given object implements the CourseUser interface.
 */
export function instanceOfCourseUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseUserFromJSON(json: any): CourseUser {
    return CourseUserFromJSONTyped(json, false);
}

export function CourseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'course': !exists(json, 'course') ? undefined : CourseFromJSON(json['course']),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function CourseUserToJSON(value?: CourseUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'courseId': value.courseId,
        'userId': value.userId,
        'course': CourseToJSON(value.course),
        'user': UserToJSON(value.user),
    };
}

