/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSimpleDTO } from './UserSimpleDTO';
import {
    UserSimpleDTOFromJSON,
    UserSimpleDTOFromJSONTyped,
    UserSimpleDTOToJSON,
} from './UserSimpleDTO';

/**
 * 
 * @export
 * @interface CourseInstanceDTO
 */
export interface CourseInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstanceDTO
     */
    courseInstanceDate?: Date;
    /**
     * 
     * @type {Array<UserSimpleDTO>}
     * @memberof CourseInstanceDTO
     */
    courseInstanceUsers?: Array<UserSimpleDTO> | null;
}

/**
 * Check if a given object implements the CourseInstanceDTO interface.
 */
export function instanceOfCourseInstanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceDTOFromJSON(json: any): CourseInstanceDTO {
    return CourseInstanceDTOFromJSONTyped(json, false);
}

export function CourseInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'courseInstanceDate': !exists(json, 'courseInstanceDate') ? undefined : (new Date(json['courseInstanceDate'])),
        'courseInstanceUsers': !exists(json, 'courseInstanceUsers') ? undefined : (json['courseInstanceUsers'] === null ? null : (json['courseInstanceUsers'] as Array<any>).map(UserSimpleDTOFromJSON)),
    };
}

export function CourseInstanceDTOToJSON(value?: CourseInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'courseId': value.courseId,
        'name': value.name,
        'description': value.description,
        'courseInstanceDate': value.courseInstanceDate === undefined ? undefined : (value.courseInstanceDate.toISOString()),
        'courseInstanceUsers': value.courseInstanceUsers === undefined ? undefined : (value.courseInstanceUsers === null ? null : (value.courseInstanceUsers as Array<any>).map(UserSimpleDTOToJSON)),
    };
}

