/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseDTO } from './CourseDTO';
import {
    CourseDTOFromJSON,
    CourseDTOFromJSONTyped,
    CourseDTOToJSON,
} from './CourseDTO';

/**
 * 
 * @export
 * @interface CourseDTOPagedResponse
 */
export interface CourseDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CourseDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<CourseDTO>}
     * @memberof CourseDTOPagedResponse
     */
    data?: Array<CourseDTO> | null;
}

/**
 * Check if a given object implements the CourseDTOPagedResponse interface.
 */
export function instanceOfCourseDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseDTOPagedResponseFromJSON(json: any): CourseDTOPagedResponse {
    return CourseDTOPagedResponseFromJSONTyped(json, false);
}

export function CourseDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(CourseDTOFromJSON)),
    };
}

export function CourseDTOPagedResponseToJSON(value?: CourseDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(CourseDTOToJSON)),
    };
}

