/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseInstanceDTO
 */
export interface CourseInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstanceDTO
     */
    courseId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseInstanceDTO
     */
    students?: Array<string> | null;
}

/**
 * Check if a given object implements the CourseInstanceDTO interface.
 */
export function instanceOfCourseInstanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CourseInstanceDTOFromJSON(json: any): CourseInstanceDTO {
    return CourseInstanceDTOFromJSONTyped(json, false);
}

export function CourseInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'students': !exists(json, 'students') ? undefined : json['students'],
    };
}

export function CourseInstanceDTOToJSON(value?: CourseInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'courseId': value.courseId,
        'students': value.students,
    };
}

