/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LaboratoryInstanceSimpleDTO } from './LaboratoryInstanceSimpleDTO';
import {
    LaboratoryInstanceSimpleDTOFromJSON,
    LaboratoryInstanceSimpleDTOFromJSONTyped,
    LaboratoryInstanceSimpleDTOToJSON,
} from './LaboratoryInstanceSimpleDTO';

/**
 * 
 * @export
 * @interface JoinUserSimpleLaboratoryInstanceDTO
 */
export interface JoinUserSimpleLaboratoryInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleLaboratoryInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleLaboratoryInstanceDTO
     */
    laboratoryInstanceId?: string;
    /**
     * 
     * @type {LaboratoryInstanceSimpleDTO}
     * @memberof JoinUserSimpleLaboratoryInstanceDTO
     */
    laboratoryInstance?: LaboratoryInstanceSimpleDTO;
}

/**
 * Check if a given object implements the JoinUserSimpleLaboratoryInstanceDTO interface.
 */
export function instanceOfJoinUserSimpleLaboratoryInstanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JoinUserSimpleLaboratoryInstanceDTOFromJSON(json: any): JoinUserSimpleLaboratoryInstanceDTO {
    return JoinUserSimpleLaboratoryInstanceDTOFromJSONTyped(json, false);
}

export function JoinUserSimpleLaboratoryInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinUserSimpleLaboratoryInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'laboratoryInstanceId': !exists(json, 'laboratoryInstanceId') ? undefined : json['laboratoryInstanceId'],
        'laboratoryInstance': !exists(json, 'laboratoryInstance') ? undefined : LaboratoryInstanceSimpleDTOFromJSON(json['laboratoryInstance']),
    };
}

export function JoinUserSimpleLaboratoryInstanceDTOToJSON(value?: JoinUserSimpleLaboratoryInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'laboratoryInstanceId': value.laboratoryInstanceId,
        'laboratoryInstance': LaboratoryInstanceSimpleDTOToJSON(value.laboratoryInstance),
    };
}

