/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseInstanceSimpleDTO } from './CourseInstanceSimpleDTO';
import {
    CourseInstanceSimpleDTOFromJSON,
    CourseInstanceSimpleDTOFromJSONTyped,
    CourseInstanceSimpleDTOToJSON,
} from './CourseInstanceSimpleDTO';

/**
 * 
 * @export
 * @interface JoinUserSimpleCourseInstanceDTO
 */
export interface JoinUserSimpleCourseInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleCourseInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleCourseInstanceDTO
     */
    courseInstanceId?: string;
    /**
     * 
     * @type {CourseInstanceSimpleDTO}
     * @memberof JoinUserSimpleCourseInstanceDTO
     */
    courseInstance?: CourseInstanceSimpleDTO;
}

/**
 * Check if a given object implements the JoinUserSimpleCourseInstanceDTO interface.
 */
export function instanceOfJoinUserSimpleCourseInstanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JoinUserSimpleCourseInstanceDTOFromJSON(json: any): JoinUserSimpleCourseInstanceDTO {
    return JoinUserSimpleCourseInstanceDTOFromJSONTyped(json, false);
}

export function JoinUserSimpleCourseInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinUserSimpleCourseInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseInstanceId': !exists(json, 'courseInstanceId') ? undefined : json['courseInstanceId'],
        'courseInstance': !exists(json, 'courseInstance') ? undefined : CourseInstanceSimpleDTOFromJSON(json['courseInstance']),
    };
}

export function JoinUserSimpleCourseInstanceDTOToJSON(value?: JoinUserSimpleCourseInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'courseInstanceId': value.courseInstanceId,
        'courseInstance': CourseInstanceSimpleDTOToJSON(value.courseInstance),
    };
}

