/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseSimpleDTO } from './CourseSimpleDTO';
import {
    CourseSimpleDTOFromJSON,
    CourseSimpleDTOFromJSONTyped,
    CourseSimpleDTOToJSON,
} from './CourseSimpleDTO';

/**
 * 
 * @export
 * @interface JoinUserSimpleCourseDTO
 */
export interface JoinUserSimpleCourseDTO {
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleCourseDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoinUserSimpleCourseDTO
     */
    courseId?: string;
    /**
     * 
     * @type {CourseSimpleDTO}
     * @memberof JoinUserSimpleCourseDTO
     */
    course?: CourseSimpleDTO;
}

/**
 * Check if a given object implements the JoinUserSimpleCourseDTO interface.
 */
export function instanceOfJoinUserSimpleCourseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JoinUserSimpleCourseDTOFromJSON(json: any): JoinUserSimpleCourseDTO {
    return JoinUserSimpleCourseDTOFromJSONTyped(json, false);
}

export function JoinUserSimpleCourseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinUserSimpleCourseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'course': !exists(json, 'course') ? undefined : CourseSimpleDTOFromJSON(json['course']),
    };
}

export function JoinUserSimpleCourseDTOToJSON(value?: JoinUserSimpleCourseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'courseId': value.courseId,
        'course': CourseSimpleDTOToJSON(value.course),
    };
}

