/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseSimpleDTO } from './CourseSimpleDTO';
import {
    CourseSimpleDTOFromJSON,
    CourseSimpleDTOFromJSONTyped,
    CourseSimpleDTOToJSON,
} from './CourseSimpleDTO';
import type { LaboratoryInstanceSimpleDTO } from './LaboratoryInstanceSimpleDTO';
import {
    LaboratoryInstanceSimpleDTOFromJSON,
    LaboratoryInstanceSimpleDTOFromJSONTyped,
    LaboratoryInstanceSimpleDTOToJSON,
} from './LaboratoryInstanceSimpleDTO';
import type { UserSimpleDTO } from './UserSimpleDTO';
import {
    UserSimpleDTOFromJSON,
    UserSimpleDTOFromJSONTyped,
    UserSimpleDTOToJSON,
} from './UserSimpleDTO';

/**
 * 
 * @export
 * @interface LaboratoryDTO
 */
export interface LaboratoryDTO {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryDTO
     */
    assistantName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryDTO
     */
    startTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LaboratoryDTO
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryDTO
     */
    location?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LaboratoryDTO
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryDTO
     */
    courseId?: string;
    /**
     * 
     * @type {CourseSimpleDTO}
     * @memberof LaboratoryDTO
     */
    course?: CourseSimpleDTO;
    /**
     * 
     * @type {Array<LaboratoryInstanceSimpleDTO>}
     * @memberof LaboratoryDTO
     */
    laboratoryInstances?: Array<LaboratoryInstanceSimpleDTO> | null;
    /**
     * 
     * @type {Array<UserSimpleDTO>}
     * @memberof LaboratoryDTO
     */
    laboratoryUsers?: Array<UserSimpleDTO> | null;
}

/**
 * Check if a given object implements the LaboratoryDTO interface.
 */
export function instanceOfLaboratoryDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryDTOFromJSON(json: any): LaboratoryDTO {
    return LaboratoryDTOFromJSONTyped(json, false);
}

export function LaboratoryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assistantName': !exists(json, 'assistantName') ? undefined : json['assistantName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'dayOfWeek': !exists(json, 'dayOfWeek') ? undefined : json['dayOfWeek'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'course': !exists(json, 'course') ? undefined : CourseSimpleDTOFromJSON(json['course']),
        'laboratoryInstances': !exists(json, 'laboratoryInstances') ? undefined : (json['laboratoryInstances'] === null ? null : (json['laboratoryInstances'] as Array<any>).map(LaboratoryInstanceSimpleDTOFromJSON)),
        'laboratoryUsers': !exists(json, 'laboratoryUsers') ? undefined : (json['laboratoryUsers'] === null ? null : (json['laboratoryUsers'] as Array<any>).map(UserSimpleDTOFromJSON)),
    };
}

export function LaboratoryDTOToJSON(value?: LaboratoryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assistantName': value.assistantName,
        'id': value.id,
        'startTime': value.startTime,
        'duration': value.duration,
        'location': value.location,
        'dayOfWeek': value.dayOfWeek,
        'courseId': value.courseId,
        'course': CourseSimpleDTOToJSON(value.course),
        'laboratoryInstances': value.laboratoryInstances === undefined ? undefined : (value.laboratoryInstances === null ? null : (value.laboratoryInstances as Array<any>).map(LaboratoryInstanceSimpleDTOToJSON)),
        'laboratoryUsers': value.laboratoryUsers === undefined ? undefined : (value.laboratoryUsers === null ? null : (value.laboratoryUsers as Array<any>).map(UserSimpleDTOToJSON)),
    };
}

