/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaboratoryInstanceAttendanceDTO
 */
export interface LaboratoryInstanceAttendanceDTO {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAttendanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAttendanceDTO
     */
    subjectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAttendanceDTO
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceAttendanceDTO
     */
    laboratoryInstanceDate?: Date;
}

/**
 * Check if a given object implements the LaboratoryInstanceAttendanceDTO interface.
 */
export function instanceOfLaboratoryInstanceAttendanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceAttendanceDTOFromJSON(json: any): LaboratoryInstanceAttendanceDTO {
    return LaboratoryInstanceAttendanceDTOFromJSONTyped(json, false);
}

export function LaboratoryInstanceAttendanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceAttendanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'subjectName': !exists(json, 'subjectName') ? undefined : json['subjectName'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'laboratoryInstanceDate': !exists(json, 'laboratoryInstanceDate') ? undefined : (new Date(json['laboratoryInstanceDate'])),
    };
}

export function LaboratoryInstanceAttendanceDTOToJSON(value?: LaboratoryInstanceAttendanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'subjectName': value.subjectName,
        'name': value.name,
        'laboratoryInstanceDate': value.laboratoryInstanceDate === undefined ? undefined : (value.laboratoryInstanceDate.toISOString()),
    };
}

