/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaboratoryInstanceSimpleDTO
 */
export interface LaboratoryInstanceSimpleDTO {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceSimpleDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceSimpleDTO
     */
    laboratoryId?: string;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceSimpleDTO
     */
    laboratoryInstanceDate?: Date;
}

/**
 * Check if a given object implements the LaboratoryInstanceSimpleDTO interface.
 */
export function instanceOfLaboratoryInstanceSimpleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceSimpleDTOFromJSON(json: any): LaboratoryInstanceSimpleDTO {
    return LaboratoryInstanceSimpleDTOFromJSONTyped(json, false);
}

export function LaboratoryInstanceSimpleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceSimpleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'laboratoryId': !exists(json, 'laboratoryId') ? undefined : json['laboratoryId'],
        'laboratoryInstanceDate': !exists(json, 'laboratoryInstanceDate') ? undefined : (new Date(json['laboratoryInstanceDate'])),
    };
}

export function LaboratoryInstanceSimpleDTOToJSON(value?: LaboratoryInstanceSimpleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'laboratoryId': value.laboratoryId,
        'laboratoryInstanceDate': value.laboratoryInstanceDate === undefined ? undefined : (value.laboratoryInstanceDate.toISOString()),
    };
}

