/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LaboratoryInstanceDTOPagedResponse } from './LaboratoryInstanceDTOPagedResponse';
import {
    LaboratoryInstanceDTOPagedResponseFromJSON,
    LaboratoryInstanceDTOPagedResponseFromJSONTyped,
    LaboratoryInstanceDTOPagedResponseToJSON,
} from './LaboratoryInstanceDTOPagedResponse';

/**
 * 
 * @export
 * @interface LaboratoryInstanceDTOPagedResponseRequestResponse
 */
export interface LaboratoryInstanceDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {LaboratoryInstanceDTOPagedResponse}
     * @memberof LaboratoryInstanceDTOPagedResponseRequestResponse
     */
    response?: LaboratoryInstanceDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LaboratoryInstanceDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LaboratoryInstanceDTOPagedResponseRequestResponse interface.
 */
export function instanceOfLaboratoryInstanceDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceDTOPagedResponseRequestResponseFromJSON(json: any): LaboratoryInstanceDTOPagedResponseRequestResponse {
    return LaboratoryInstanceDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function LaboratoryInstanceDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : LaboratoryInstanceDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LaboratoryInstanceDTOPagedResponseRequestResponseToJSON(value?: LaboratoryInstanceDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': LaboratoryInstanceDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

