/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LaboratoryInstance } from './LaboratoryInstance';
import {
    LaboratoryInstanceFromJSON,
    LaboratoryInstanceFromJSONTyped,
    LaboratoryInstanceToJSON,
} from './LaboratoryInstance';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface LaboratoryInstanceUser
 */
export interface LaboratoryInstanceUser {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceUser
     */
    laboratoryInstanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceUser
     */
    userId?: string;
    /**
     * 
     * @type {LaboratoryInstance}
     * @memberof LaboratoryInstanceUser
     */
    laboratoryInstance?: LaboratoryInstance;
    /**
     * 
     * @type {User}
     * @memberof LaboratoryInstanceUser
     */
    user?: User;
}

/**
 * Check if a given object implements the LaboratoryInstanceUser interface.
 */
export function instanceOfLaboratoryInstanceUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceUserFromJSON(json: any): LaboratoryInstanceUser {
    return LaboratoryInstanceUserFromJSONTyped(json, false);
}

export function LaboratoryInstanceUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'laboratoryInstanceId': !exists(json, 'laboratoryInstanceId') ? undefined : json['laboratoryInstanceId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'laboratoryInstance': !exists(json, 'laboratoryInstance') ? undefined : LaboratoryInstanceFromJSON(json['laboratoryInstance']),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function LaboratoryInstanceUserToJSON(value?: LaboratoryInstanceUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'laboratoryInstanceId': value.laboratoryInstanceId,
        'userId': value.userId,
        'laboratoryInstance': LaboratoryInstanceToJSON(value.laboratoryInstance),
        'user': UserToJSON(value.user),
    };
}

