/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { LaboratoryDTO } from './LaboratoryDTO';
import {
    LaboratoryDTOFromJSON,
    LaboratoryDTOFromJSONTyped,
    LaboratoryDTOToJSON,
} from './LaboratoryDTO';

/**
 * 
 * @export
 * @interface LaboratoryDTORequestResponse
 */
export interface LaboratoryDTORequestResponse {
    /**
     * 
     * @type {LaboratoryDTO}
     * @memberof LaboratoryDTORequestResponse
     */
    response?: LaboratoryDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LaboratoryDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the LaboratoryDTORequestResponse interface.
 */
export function instanceOfLaboratoryDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryDTORequestResponseFromJSON(json: any): LaboratoryDTORequestResponse {
    return LaboratoryDTORequestResponseFromJSONTyped(json, false);
}

export function LaboratoryDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : LaboratoryDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LaboratoryDTORequestResponseToJSON(value?: LaboratoryDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': LaboratoryDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

