/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaboratoryInstanceAddDTO
 */
export interface LaboratoryInstanceAddDTO {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAddDTO
     */
    laboratoryId?: string;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceAddDTO
     */
    laboratoryInstanceDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the LaboratoryInstanceAddDTO interface.
 */
export function instanceOfLaboratoryInstanceAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceAddDTOFromJSON(json: any): LaboratoryInstanceAddDTO {
    return LaboratoryInstanceAddDTOFromJSONTyped(json, false);
}

export function LaboratoryInstanceAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'laboratoryId': !exists(json, 'laboratoryId') ? undefined : json['laboratoryId'],
        'laboratoryInstanceDate': !exists(json, 'laboratoryInstanceDate') ? undefined : (new Date(json['laboratoryInstanceDate'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function LaboratoryInstanceAddDTOToJSON(value?: LaboratoryInstanceAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'laboratoryId': value.laboratoryId,
        'laboratoryInstanceDate': value.laboratoryInstanceDate === undefined ? undefined : (value.laboratoryInstanceDate.toISOString()),
        'name': value.name,
        'description': value.description,
    };
}

