/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LaboratoryInstanceDTO } from './LaboratoryInstanceDTO';
import {
    LaboratoryInstanceDTOFromJSON,
    LaboratoryInstanceDTOFromJSONTyped,
    LaboratoryInstanceDTOToJSON,
} from './LaboratoryInstanceDTO';

/**
 * 
 * @export
 * @interface LaboratoryInstanceDTOPagedResponse
 */
export interface LaboratoryInstanceDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof LaboratoryInstanceDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof LaboratoryInstanceDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof LaboratoryInstanceDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<LaboratoryInstanceDTO>}
     * @memberof LaboratoryInstanceDTOPagedResponse
     */
    data?: Array<LaboratoryInstanceDTO> | null;
}

/**
 * Check if a given object implements the LaboratoryInstanceDTOPagedResponse interface.
 */
export function instanceOfLaboratoryInstanceDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceDTOPagedResponseFromJSON(json: any): LaboratoryInstanceDTOPagedResponse {
    return LaboratoryInstanceDTOPagedResponseFromJSONTyped(json, false);
}

export function LaboratoryInstanceDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(LaboratoryInstanceDTOFromJSON)),
    };
}

export function LaboratoryInstanceDTOPagedResponseToJSON(value?: LaboratoryInstanceDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(LaboratoryInstanceDTOToJSON)),
    };
}

