/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSimpleDTO } from './UserSimpleDTO';
import {
    UserSimpleDTOFromJSON,
    UserSimpleDTOFromJSONTyped,
    UserSimpleDTOToJSON,
} from './UserSimpleDTO';

/**
 * 
 * @export
 * @interface LaboratoryInstanceDTO
 */
export interface LaboratoryInstanceDTO {
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryInstanceDTO
     */
    laboratoryId?: string;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryInstanceDTO
     */
    laboratoryInstanceDate?: Date;
    /**
     * 
     * @type {Array<UserSimpleDTO>}
     * @memberof LaboratoryInstanceDTO
     */
    students?: Array<UserSimpleDTO> | null;
}

/**
 * Check if a given object implements the LaboratoryInstanceDTO interface.
 */
export function instanceOfLaboratoryInstanceDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryInstanceDTOFromJSON(json: any): LaboratoryInstanceDTO {
    return LaboratoryInstanceDTOFromJSONTyped(json, false);
}

export function LaboratoryInstanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryInstanceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'laboratoryId': !exists(json, 'laboratoryId') ? undefined : json['laboratoryId'],
        'laboratoryInstanceDate': !exists(json, 'laboratoryInstanceDate') ? undefined : (new Date(json['laboratoryInstanceDate'])),
        'students': !exists(json, 'students') ? undefined : (json['students'] === null ? null : (json['students'] as Array<any>).map(UserSimpleDTOFromJSON)),
    };
}

export function LaboratoryInstanceDTOToJSON(value?: LaboratoryInstanceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'laboratoryId': value.laboratoryId,
        'laboratoryInstanceDate': value.laboratoryInstanceDate === undefined ? undefined : (value.laboratoryInstanceDate.toISOString()),
        'students': value.students === undefined ? undefined : (value.students === null ? null : (value.students as Array<any>).map(UserSimpleDTOToJSON)),
    };
}

