/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentToLaboratoryAddDTO
 */
export interface StudentToLaboratoryAddDTO {
    /**
     * 
     * @type {string}
     * @memberof StudentToLaboratoryAddDTO
     */
    laboratoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentToLaboratoryAddDTO
     */
    studentId?: string;
}

/**
 * Check if a given object implements the StudentToLaboratoryAddDTO interface.
 */
export function instanceOfStudentToLaboratoryAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentToLaboratoryAddDTOFromJSON(json: any): StudentToLaboratoryAddDTO {
    return StudentToLaboratoryAddDTOFromJSONTyped(json, false);
}

export function StudentToLaboratoryAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentToLaboratoryAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'laboratoryId': !exists(json, 'laboratoryId') ? undefined : json['laboratoryId'],
        'studentId': !exists(json, 'studentId') ? undefined : json['studentId'],
    };
}

export function StudentToLaboratoryAddDTOToJSON(value?: StudentToLaboratoryAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'laboratoryId': value.laboratoryId,
        'studentId': value.studentId,
    };
}

