/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentToCourseAddDTO
 */
export interface StudentToCourseAddDTO {
    /**
     * 
     * @type {string}
     * @memberof StudentToCourseAddDTO
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentToCourseAddDTO
     */
    studentId?: string;
}

/**
 * Check if a given object implements the StudentToCourseAddDTO interface.
 */
export function instanceOfStudentToCourseAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentToCourseAddDTOFromJSON(json: any): StudentToCourseAddDTO {
    return StudentToCourseAddDTOFromJSONTyped(json, false);
}

export function StudentToCourseAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentToCourseAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'studentId': !exists(json, 'studentId') ? undefined : json['studentId'],
    };
}

export function StudentToCourseAddDTOToJSON(value?: StudentToCourseAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseId': value.courseId,
        'studentId': value.studentId,
    };
}

