/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { SubjectDTOPagedResponse } from './SubjectDTOPagedResponse';
import {
    SubjectDTOPagedResponseFromJSON,
    SubjectDTOPagedResponseFromJSONTyped,
    SubjectDTOPagedResponseToJSON,
} from './SubjectDTOPagedResponse';

/**
 * 
 * @export
 * @interface SubjectDTOPagedResponseRequestResponse
 */
export interface SubjectDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {SubjectDTOPagedResponse}
     * @memberof SubjectDTOPagedResponseRequestResponse
     */
    response?: SubjectDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof SubjectDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the SubjectDTOPagedResponseRequestResponse interface.
 */
export function instanceOfSubjectDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectDTOPagedResponseRequestResponseFromJSON(json: any): SubjectDTOPagedResponseRequestResponse {
    return SubjectDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function SubjectDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : SubjectDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function SubjectDTOPagedResponseRequestResponseToJSON(value?: SubjectDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': SubjectDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

