/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Course } from './Course';
import {
    CourseFromJSON,
    CourseFromJSONTyped,
    CourseToJSON,
} from './Course';
import type { Laboratory } from './Laboratory';
import {
    LaboratoryFromJSON,
    LaboratoryFromJSONTyped,
    LaboratoryToJSON,
} from './Laboratory';

/**
 * 
 * @export
 * @interface Subject
 */
export interface Subject {
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Subject
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Subject
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    year?: string;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    professor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    creditsNo?: string;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    description?: string | null;
    /**
     * 
     * @type {Course}
     * @memberof Subject
     */
    course?: Course;
    /**
     * 
     * @type {Array<Laboratory>}
     * @memberof Subject
     */
    laboratories?: Array<Laboratory> | null;
}

/**
 * Check if a given object implements the Subject interface.
 */
export function instanceOfSubject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectFromJSON(json: any): Subject {
    return SubjectFromJSONTyped(json, false);
}

export function SubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'professor': !exists(json, 'professor') ? undefined : json['professor'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'creditsNo': !exists(json, 'creditsNo') ? undefined : json['creditsNo'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'course': !exists(json, 'course') ? undefined : CourseFromJSON(json['course']),
        'laboratories': !exists(json, 'laboratories') ? undefined : (json['laboratories'] === null ? null : (json['laboratories'] as Array<any>).map(LaboratoryFromJSON)),
    };
}

export function SubjectToJSON(value?: Subject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'name': value.name,
        'year': value.year,
        'professor': value.professor,
        'department': value.department,
        'creditsNo': value.creditsNo,
        'description': value.description,
        'course': CourseToJSON(value.course),
        'laboratories': value.laboratories === undefined ? undefined : (value.laboratories === null ? null : (value.laboratories as Array<any>).map(LaboratoryToJSON)),
    };
}

