/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubjectUser } from './SubjectUser';
import {
    SubjectUserFromJSON,
    SubjectUserFromJSONTyped,
    SubjectUserToJSON,
} from './SubjectUser';

/**
 * 
 * @export
 * @interface SubjectUpdateDTO
 */
export interface SubjectUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    year?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    semester?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    creditsNo?: string | null;
    /**
     * 
     * @type {Array<SubjectUser>}
     * @memberof SubjectUpdateDTO
     */
    subjectUsers?: Array<SubjectUser> | null;
}

/**
 * Check if a given object implements the SubjectUpdateDTO interface.
 */
export function instanceOfSubjectUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectUpdateDTOFromJSON(json: any): SubjectUpdateDTO {
    return SubjectUpdateDTOFromJSONTyped(json, false);
}

export function SubjectUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'semester': !exists(json, 'semester') ? undefined : json['semester'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'creditsNo': !exists(json, 'creditsNo') ? undefined : json['creditsNo'],
        'subjectUsers': !exists(json, 'subjectUsers') ? undefined : (json['subjectUsers'] === null ? null : (json['subjectUsers'] as Array<any>).map(SubjectUserFromJSON)),
    };
}

export function SubjectUpdateDTOToJSON(value?: SubjectUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'year': value.year,
        'semester': value.semester,
        'department': value.department,
        'description': value.description,
        'creditsNo': value.creditsNo,
        'subjectUsers': value.subjectUsers === undefined ? undefined : (value.subjectUsers === null ? null : (value.subjectUsers as Array<any>).map(SubjectUserToJSON)),
    };
}

