/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSimpleDTO } from './UserSimpleDTO';
import {
    UserSimpleDTOFromJSON,
    UserSimpleDTOFromJSONTyped,
    UserSimpleDTOToJSON,
} from './UserSimpleDTO';

/**
 * 
 * @export
 * @interface SubjectUserSimpleDTO
 */
export interface SubjectUserSimpleDTO {
    /**
     * 
     * @type {string}
     * @memberof SubjectUserSimpleDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectUserSimpleDTO
     */
    userId?: string;
    /**
     * 
     * @type {UserSimpleDTO}
     * @memberof SubjectUserSimpleDTO
     */
    user?: UserSimpleDTO;
}

/**
 * Check if a given object implements the SubjectUserSimpleDTO interface.
 */
export function instanceOfSubjectUserSimpleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectUserSimpleDTOFromJSON(json: any): SubjectUserSimpleDTO {
    return SubjectUserSimpleDTOFromJSONTyped(json, false);
}

export function SubjectUserSimpleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectUserSimpleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserSimpleDTOFromJSON(json['user']),
    };
}

export function SubjectUserSimpleDTOToJSON(value?: SubjectUserSimpleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'user': UserSimpleDTOToJSON(value.user),
    };
}

