/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface SubjectUser
 */
export interface SubjectUser {
    /**
     * 
     * @type {string}
     * @memberof SubjectUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SubjectUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubjectUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof SubjectUser
     */
    subjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectUser
     */
    userId?: string;
    /**
     * 
     * @type {Subject}
     * @memberof SubjectUser
     */
    subject?: Subject;
    /**
     * 
     * @type {User}
     * @memberof SubjectUser
     */
    user?: User;
}

/**
 * Check if a given object implements the SubjectUser interface.
 */
export function instanceOfSubjectUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectUserFromJSON(json: any): SubjectUser {
    return SubjectUserFromJSONTyped(json, false);
}

export function SubjectUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'subject': !exists(json, 'subject') ? undefined : SubjectFromJSON(json['subject']),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function SubjectUserToJSON(value?: SubjectUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'subjectId': value.subjectId,
        'userId': value.userId,
        'subject': SubjectToJSON(value.subject),
        'user': UserToJSON(value.user),
    };
}

