/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { SubjectDTO } from './SubjectDTO';
import {
    SubjectDTOFromJSON,
    SubjectDTOFromJSONTyped,
    SubjectDTOToJSON,
} from './SubjectDTO';

/**
 * 
 * @export
 * @interface SubjectDTORequestResponse
 */
export interface SubjectDTORequestResponse {
    /**
     * 
     * @type {SubjectDTO}
     * @memberof SubjectDTORequestResponse
     */
    response?: SubjectDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof SubjectDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the SubjectDTORequestResponse interface.
 */
export function instanceOfSubjectDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectDTORequestResponseFromJSON(json: any): SubjectDTORequestResponse {
    return SubjectDTORequestResponseFromJSONTyped(json, false);
}

export function SubjectDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : SubjectDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function SubjectDTORequestResponseToJSON(value?: SubjectDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': SubjectDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

