/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimetableClassesDTO
 */
export interface TimetableClassesDTO {
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    classId?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    startTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    location?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TimetableClassesDTO
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    dayOfWeekPrint?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    subjectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimetableClassesDTO
     */
    type?: string | null;
}

/**
 * Check if a given object implements the TimetableClassesDTO interface.
 */
export function instanceOfTimetableClassesDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimetableClassesDTOFromJSON(json: any): TimetableClassesDTO {
    return TimetableClassesDTOFromJSONTyped(json, false);
}

export function TimetableClassesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableClassesDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classId': !exists(json, 'classId') ? undefined : json['classId'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'dayOfWeek': !exists(json, 'dayOfWeek') ? undefined : json['dayOfWeek'],
        'dayOfWeekPrint': !exists(json, 'dayOfWeekPrint') ? undefined : json['dayOfWeekPrint'],
        'subjectName': !exists(json, 'subjectName') ? undefined : json['subjectName'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TimetableClassesDTOToJSON(value?: TimetableClassesDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classId': value.classId,
        'startTime': value.startTime,
        'location': value.location,
        'dayOfWeek': value.dayOfWeek,
        'dayOfWeekPrint': value.dayOfWeekPrint,
        'subjectName': value.subjectName,
        'type': value.type,
    };
}

