/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TimetableClassesDTO } from './TimetableClassesDTO';
import {
    TimetableClassesDTOFromJSON,
    TimetableClassesDTOFromJSONTyped,
    TimetableClassesDTOToJSON,
} from './TimetableClassesDTO';

/**
 * 
 * @export
 * @interface TimetableClassesDTOICollectionRequestResponse
 */
export interface TimetableClassesDTOICollectionRequestResponse {
    /**
     * 
     * @type {Array<TimetableClassesDTO>}
     * @memberof TimetableClassesDTOICollectionRequestResponse
     */
    readonly response?: Array<TimetableClassesDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TimetableClassesDTOICollectionRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TimetableClassesDTOICollectionRequestResponse interface.
 */
export function instanceOfTimetableClassesDTOICollectionRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimetableClassesDTOICollectionRequestResponseFromJSON(json: any): TimetableClassesDTOICollectionRequestResponse {
    return TimetableClassesDTOICollectionRequestResponseFromJSONTyped(json, false);
}

export function TimetableClassesDTOICollectionRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableClassesDTOICollectionRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(TimetableClassesDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TimetableClassesDTOICollectionRequestResponseToJSON(value?: TimetableClassesDTOICollectionRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

