/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersToSubjectAddDTO
 */
export interface UsersToSubjectAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UsersToSubjectAddDTO
     */
    subjectId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UsersToSubjectAddDTO
     */
    userIds?: Array<string> | null;
}

/**
 * Check if a given object implements the UsersToSubjectAddDTO interface.
 */
export function instanceOfUsersToSubjectAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersToSubjectAddDTOFromJSON(json: any): UsersToSubjectAddDTO {
    return UsersToSubjectAddDTOFromJSONTyped(json, false);
}

export function UsersToSubjectAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersToSubjectAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'userIds': !exists(json, 'userIds') ? undefined : json['userIds'],
    };
}

export function UsersToSubjectAddDTOToJSON(value?: UsersToSubjectAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subjectId': value.subjectId,
        'userIds': value.userIds,
    };
}

