/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface UserSimpleDTO
 */
export interface UserSimpleDTO {
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDTO
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserSimpleDTO
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDTO
     */
    group?: string | null;
}

/**
 * Check if a given object implements the UserSimpleDTO interface.
 */
export function instanceOfUserSimpleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserSimpleDTOFromJSON(json: any): UserSimpleDTO {
    return UserSimpleDTOFromJSONTyped(json, false);
}

export function UserSimpleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSimpleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
        'group': !exists(json, 'group') ? undefined : json['group'],
    };
}

export function UserSimpleDTOToJSON(value?: UserSimpleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'role': UserRoleEnumToJSON(value.role),
        'group': value.group,
    };
}

