/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserToCourseAddDTO
 */
export interface UserToCourseAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserToCourseAddDTO
     */
    courseId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserToCourseAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserToCourseAddDTO interface.
 */
export function instanceOfUserToCourseAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserToCourseAddDTOFromJSON(json: any): UserToCourseAddDTO {
    return UserToCourseAddDTOFromJSONTyped(json, false);
}

export function UserToCourseAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserToCourseAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function UserToCourseAddDTOToJSON(value?: UserToCourseAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseId': value.courseId,
        'userId': value.userId,
    };
}

