/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateDTO
 */
export interface UserUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    password?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserUpdateDTO
     */
    laboratories?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserUpdateDTO
     */
    courses?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserUpdateDTO
     */
    laboratoryInstances?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserUpdateDTO
     */
    courseInstances?: Array<string> | null;
}

/**
 * Check if a given object implements the UserUpdateDTO interface.
 */
export function instanceOfUserUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUpdateDTOFromJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOFromJSONTyped(json, false);
}

export function UserUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'laboratories': !exists(json, 'laboratories') ? undefined : json['laboratories'],
        'courses': !exists(json, 'courses') ? undefined : json['courses'],
        'laboratoryInstances': !exists(json, 'laboratoryInstances') ? undefined : json['laboratoryInstances'],
        'courseInstances': !exists(json, 'courseInstances') ? undefined : json['courseInstances'],
    };
}

export function UserUpdateDTOToJSON(value?: UserUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'password': value.password,
        'laboratories': value.laboratories,
        'courses': value.courses,
        'laboratoryInstances': value.laboratoryInstances,
        'courseInstances': value.courseInstances,
    };
}

