/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserToCourseInstanceAddDTO
 */
export interface UserToCourseInstanceAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserToCourseInstanceAddDTO
     */
    courseInstanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserToCourseInstanceAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserToCourseInstanceAddDTO interface.
 */
export function instanceOfUserToCourseInstanceAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserToCourseInstanceAddDTOFromJSON(json: any): UserToCourseInstanceAddDTO {
    return UserToCourseInstanceAddDTOFromJSONTyped(json, false);
}

export function UserToCourseInstanceAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserToCourseInstanceAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseInstanceId': !exists(json, 'courseInstanceId') ? undefined : json['courseInstanceId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function UserToCourseInstanceAddDTOToJSON(value?: UserToCourseInstanceAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseInstanceId': value.courseInstanceId,
        'userId': value.userId,
    };
}

