/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserToLaboratoryInstanceAddDTO
 */
export interface UserToLaboratoryInstanceAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserToLaboratoryInstanceAddDTO
     */
    laboratoryInstanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserToLaboratoryInstanceAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserToLaboratoryInstanceAddDTO interface.
 */
export function instanceOfUserToLaboratoryInstanceAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserToLaboratoryInstanceAddDTOFromJSON(json: any): UserToLaboratoryInstanceAddDTO {
    return UserToLaboratoryInstanceAddDTOFromJSONTyped(json, false);
}

export function UserToLaboratoryInstanceAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserToLaboratoryInstanceAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'laboratoryInstanceId': !exists(json, 'laboratoryInstanceId') ? undefined : json['laboratoryInstanceId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function UserToLaboratoryInstanceAddDTOToJSON(value?: UserToLaboratoryInstanceAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'laboratoryInstanceId': value.laboratoryInstanceId,
        'userId': value.userId,
    };
}

