/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserToSubjectAddDTO
 */
export interface UserToSubjectAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserToSubjectAddDTO
     */
    subjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserToSubjectAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the UserToSubjectAddDTO interface.
 */
export function instanceOfUserToSubjectAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserToSubjectAddDTOFromJSON(json: any): UserToSubjectAddDTO {
    return UserToSubjectAddDTOFromJSONTyped(json, false);
}

export function UserToSubjectAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserToSubjectAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function UserToSubjectAddDTOToJSON(value?: UserToSubjectAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subjectId': value.subjectId,
        'userId': value.userId,
    };
}

